#!/bin/bash
# Quick Start Guide for Maximum FPS

echo "=========================================="
echo "Fish Mortality Detection - Performance Info"
echo "=========================================="
echo ""
echo "Current Configuration:"
echo "  • Camera: 960x540 @ 25 FPS"
echo "  • YOLO: 320x320 input size"
echo "  • Detection: Every 8th frame (~3 FPS)"
echo "  • Behavior Analysis: Disabled"
echo ""
echo "Expected Performance:"
echo "  • Display FPS: 24-25 (smooth video) ✓"
echo "  • Detection FPS: 2-3 (adequate for fish) ✓"
echo ""
echo "=========================================="
echo "Available Modes:"
echo "=========================================="
echo ""
echo "1. Full System (with mortality detection)"
echo "   ./start.sh"
echo "   - Complete fish monitoring"
echo "   - Mortality alerts enabled"
echo "   - Rainfall detection"
echo ""
echo "2. Ultra-Fast View (detection only)"
echo "   python3 live_view_fast.py"
echo "   - Basic fish detection"
echo "   - No behavior analysis"
echo "   - Maximum FPS"
echo ""
echo "3. Performance Test"
echo "   python3 test_performance.py"
echo "   - Benchmark YOLOv8 speed"
echo "   - Shows inference times"
echo "   - Recommends settings"
echo ""
echo "=========================================="
echo "Why Detection FPS is Low (2-3 FPS):"
echo "=========================================="
echo ""
echo "This is NORMAL for Raspberry Pi 4!"
echo ""
echo "• YOLOv8 is a heavy deep learning model"
echo "• Pi 4 CPU: ARM Cortex-A72 @ 1.5GHz"
echo "• No GPU acceleration available"
echo "• 320x320 inference takes 400-500ms"
echo ""
echo "But this is SUFFICIENT because:"
echo "✓ Fish mortality is gradual (minutes/hours)"
echo "✓ 2-3 det/sec = 120-180 checks/minute"
echo "✓ Display still runs at 25 FPS (smooth)"
echo "✓ Early detection still works perfectly"
echo ""
echo "=========================================="
echo "To Improve Detection FPS:"
echo "=========================================="
echo ""
echo "Software Options:"
echo "  1. Increase SKIP_FRAMES to 10 or 12"
echo "     (reduces load, display still smooth)"
echo ""
echo "  2. Use smaller resolution (640x480)"
echo "     (faster but less detail)"
echo ""
echo "  3. Enable CPU performance mode:"
echo "     echo performance | sudo tee /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor"
echo ""
echo "Hardware Options:"
echo "  • Google Coral USB Accelerator ($60)"
echo "    → 100-400 FPS with Edge TPU"
echo ""
echo "  • Intel Neural Compute Stick 2 ($70)"
echo "    → 20-50 FPS with VPU"
echo ""
echo "  • Overclock Pi 4 (requires cooling)"
echo "    → 1.5 GHz → 1.8-2.0 GHz"
echo ""
echo "=========================================="
echo "System Status Check:"
echo "=========================================="
echo ""

# Check CPU frequency
echo -n "CPU Frequency: "
vcgencmd measure_clock arm | awk -F'=' '{printf "%.0f MHz\n", $2/1000000}'

# Check CPU temperature
echo -n "CPU Temperature: "
vcgencmd measure_temp | awk -F'=' '{print $2}'

# Check CPU governor
echo -n "CPU Governor: "
cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor 2>/dev/null || echo "Unknown"

# Check memory
echo -n "Memory Available: "
free -h | awk '/^Mem:/ {print $7}'

echo ""
echo "=========================================="
echo "Ready to start! Choose a mode above."
echo "=========================================="
